name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '~1.11.0'

      - name: Create virtual environment
        run: python3 -m venv --upgrade-deps .venv

      - name: Install dependencies
        run: .venv/bin/pip install .[dev]

      - name: Check formatting
        run: make format-check

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
