name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

env:
  GCP_PROJECT: ${{ vars.GCP_PROJECT || 'dft-ate-api-common' }}
  GCP_LOCATION: ${{ vars.GCP_LOCATION || 'europe-west1' }}
  GCP_REPOSITORY_ID: docker
  IMAGE_NAME: ate-api
  IMAGE_REFERENCE: ${{ env.GCP_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.GCP_REPOSITORY_ID }}/${{ env.IMAGE_NAME }}
  GCP_SERVICE_NAME: ate-api

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '~1.11.0'

      - name: Create virtual environment
        run: python3 -m venv --upgrade-deps .venv

      - name: Install dependencies
        run: .venv/bin/pip install .[dev]

      - name: Check formatting
        run: make format-check

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          credentials_json: '${{ secrets.GCP_CREDENTIALS_PUSH }}'

      - name: Login to Docker repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCP_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: meta
        name: Extract metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REFERENCE }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_DEPLOY }}'

      - name: Deploy image
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_SERVICE_NAME }}
          image: ${{ env.IMAGE_REFERENCE }}
          region: ${{ env.GCP_LOCATION }}
